global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'friends-service'
    static_configs:
      - targets: ['friends-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s