apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-v2
  labels:
    app: users
    version: v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: users
      version: v2
  template:
    metadata:
      labels:
        app: users
        version: v2
    spec:
      containers:
      - name: users
        image: users-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: PORT
          value: "8004"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5