apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    color: green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth
      color: green
  template:
    metadata:
      labels:
        app: auth
        color: green
    spec:
      containers:
        - name: auth
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: PORT
              value: "8001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5